class Url:
    BASE_PAGE = 'https://byrotation.com/'
    JOURNAL_PAGE = 'https://journal.byrotation.com/'
    FAQ_PAGE = 'https://faq.byrotation.com/hc/en-gb'
    NEW_IN_PAGE_PATH = 'new-in'
    DESIGNERS_PAGE_PATH = 'designers'
    COLLECTIONS_PAGE_PATH = 'collections'
    DRESSES_PAGE_PATH = 'category/women/dresses'
    CLOTHING_PAGE_PATH = 'category/women'
    ACCESSORIES_PAGE_PATH = 'category/women/accessories'
    MEN_PAGE_PATH = 'category/men'
    RESALE_PAGE_PATH = 'collections/resale'
    COMMUNITY_PAGE_PATH = 'the-community'
    OUR_STORY_PAGE_PATH = 'our-story'
    CHARITY_PAGE_PATH = 'charity'
    EVENTS_PAGE_PATH = 'events'
    GIFT_CARD_PAGE_PATH = 'gift-card'
    HOW_IT_WORKS_PAGE_PATH = 'how-it-works'
    SUSTAINABILITY_PAGE_PATH = 'sustainability'
    PRESS_PAGE_PATH = 'press'
    OUR_APP_PAGE_PATH = 'our-app'
    MAILER_BAGS_PAGE_PATH = 'product/compostable-mailer-bags'
    TOTE_BAG_PAGE_PATH = 'product/tote-bag'
    EMAIL_US_PAGE_PATH = 'hc/en-gb/requests/new'


class TDSearch:
    BRAND_1 = 'Dior'
    BRAND_2 = 'Gucci'
    BRAND_3 = 'Chanel'
    BRAND_4 = 'Prada'
    BRAND_5 = 'Jacquemus'
    PRODUCT_TYPE_1 = 'Shoes'
    PRODUCT_TYPE_2 = 'Jacket'
    PRODUCT_TYPE_3 = 'Bag'
    PRODUCT_COLOUR_1 = 'Black'
    PRODUCT_COLOUR_2 = 'Green'
    PRODUCT_COLOUR_3 = 'Blue'
