from selenium.webdriver.common.by import By
from locators.base_page_locators import BasePageLocators


class FilterPageLocators(BasePageLocators):
    SCROLL = By.XPATH, "//*[@data-test-id='virtuoso-scroller']"
    CATEGORY_BUTTON = By.XPATH, "//h3[text()='Category']"
    PRODUCT_TYPE_BUTTON = By.XPATH, "//h3[text()='Product Type']"
    BRAND_BUTTON = By.XPATH, "//h3[text()='Brand']"
    SUBCATEGORY_BUTTON = By.XPATH, "//h3[text()='Subcategory']"
    SIZE_BUTTON = By.XPATH, "//h3[text()='Size']"
    COLOUR_BUTTON = By.XPATH, "//h3[text()='Colour']"
    COLLECTION_BUTTON = By.XPATH, "//h3[text()='Collection']"
    PRICE_PER_DAY_BUTTON = By.XPATH, "//h3[text()='Price Per Day']"
    POSTAGE_BUTTON = By.XPATH, "//h3[text()='Postage Available']"
    RESALE_BUTTON = By.XPATH, "//h3[text()='Resale Available']"
    WOMEN_CHECK_BOX = By.XPATH, "//p[contains(text(), 'Women')]"
    MEN_CHECK_BOX = By.XPATH, "//p[contains(text(), 'Men')]"
    DRESSES_CHECKBOX = By.XPATH, "//p[contains(text(), 'Dresses')]"
    BAGS_CHECKBOX = By.XPATH, "//p[contains(text(), 'Bags')]"
    TOPS_CHECKBOX = By.XPATH, "//p[contains(text(), 'Tops')]"
    COATS_CHECKBOX = By.XPATH, "//p[contains(text(), 'Coats')]"
    RIXO_CHECKBOX = By.XPATH, "//p[contains(text(), 'Rixo')]"
    HANDBAG_CHECKBOX = By.XPATH, "//p[contains(text(), 'Handbag')]"
    SIZE_4_CHECKBOX = By.XPATH, "//p[text()='UK 4']"
    BLACK_CHECKBOX = By.XPATH, "//p[text()='Black']"
    WEDDING_GUEST_CHECKBOX = By.XPATH, "//p[contains(text(), 'Wedding Guest')]"
    WOMEN_LABEL = By.XPATH, "//span[text()='Women']"
    MEN_LABEL = By.XPATH, "//span[text()='Men']"
    BAGS_LABEL = By.XPATH, "//span[text()='Bags']"
    TOPS_LABEL = By.XPATH, "//span[text()='Tops']"
    RIXO_LABEL = By.XPATH, "//span[text()='Rixo']"
    HANDBAG_LABEL = By.XPATH, "//span[text()='Handbags']"
    SIZE_4_LABEL = By.XPATH, "//span[text()='UK4']"
    BLACK_LABEL = By.XPATH, "//span[text()='Black']"
    WEDDING_GUEST_LABEL = By.XPATH, "//span[text()='Wedding Guest']"
    WEDDING_GUEST_PHOTO_LABEL = By.XPATH, "//p[text()='Wedding Guest']"
    MIN_BUTTON = By.XPATH, "//p[text()='Min: £2']"
    MAX_BUTTON = By.XPATH, "//p[text()='Max: £1380']"
    MIN_INPUT = By.XPATH, "//input[@value='2']"
    MAX_INPUT = By.XPATH, "//input[@value='1380']"
